spring:
  datasource:
    url: jdbc:mysql://192.168.31.231:3306/dev?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456

    redis:
        host: 192.168.31.231
        port: 6379

server:
  port: 8080

logging:
  config: classpath:logback-spring.xml
  level: debug
